cpu_mem_usage moved to an internal config variable in python
flux-framework/PerfFlowAspect pull request #81
Opened 2022-10-21 22:16 UTC by alizalisan

2023-02-23 21:31 UTC, tpatki commented
@slabasan LGTM. I can hit merge but I'll let you review it too :)

2023-02-23 21:33 UTC, tpatki approved these changes

2023-02-24 22:03 UTC, slabasan requested changes

2023-02-24 22:30 UTC, slabasan approved these changes

2023-02-24 22:31 UTC, merged